//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD35Entities : DbContext
    {
        public BD35Entities()
            : base("name=BD35Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SS_DDJJ_1874_Result> SS_DDJJ_1874(string codigo_movto, string moneda, string fechaInicio, string fechaFin)
        {
            var codigo_movtoParameter = codigo_movto != null ?
                new ObjectParameter("Codigo_movto", codigo_movto) :
                new ObjectParameter("Codigo_movto", typeof(string));
    
            var monedaParameter = moneda != null ?
                new ObjectParameter("Moneda", moneda) :
                new ObjectParameter("Moneda", typeof(string));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(string));
    
            var fechaFinParameter = fechaFin != null ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SS_DDJJ_1874_Result>("SS_DDJJ_1874", codigo_movtoParameter, monedaParameter, fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<SS_DDJJ_1922_Result> SS_DDJJ_1922(string codigo_movto, string fechaInicio, string fechaFin)
        {
            var codigo_movtoParameter = codigo_movto != null ?
                new ObjectParameter("Codigo_movto", codigo_movto) :
                new ObjectParameter("Codigo_movto", typeof(string));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(string));
    
            var fechaFinParameter = fechaFin != null ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SS_DDJJ_1922_Result>("SS_DDJJ_1922", codigo_movtoParameter, fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<SS_DDJJ_1949_Result> SS_DDJJ_1949(string codigo_movto, string fechaInicio, string fechaFin)
        {
            var codigo_movtoParameter = codigo_movto != null ?
                new ObjectParameter("Codigo_movto", codigo_movto) :
                new ObjectParameter("Codigo_movto", typeof(string));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(string));
    
            var fechaFinParameter = fechaFin != null ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SS_DDJJ_1949_Result>("SS_DDJJ_1949", codigo_movtoParameter, fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<SS_DDJJ_1932_Result> SS_DDJJ_1932(string codigo_movto, string moneda, string fechaInicio, string fechaFin)
        {
            var codigo_movtoParameter = codigo_movto != null ?
                new ObjectParameter("Codigo_movto", codigo_movto) :
                new ObjectParameter("Codigo_movto", typeof(string));
    
            var monedaParameter = moneda != null ?
                new ObjectParameter("Moneda", moneda) :
                new ObjectParameter("Moneda", typeof(string));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(string));
    
            var fechaFinParameter = fechaFin != null ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SS_DDJJ_1932_Result>("SS_DDJJ_1932", codigo_movtoParameter, monedaParameter, fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<SS_DDJJ_ObtenerTipoEvento_Result> SS_DDJJ_ObtenerTipoEvento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SS_DDJJ_ObtenerTipoEvento_Result>("SS_DDJJ_ObtenerTipoEvento");
        }
    
        public virtual ObjectResult<SS_DDJJ_ObtenerMoneda_Result> SS_DDJJ_ObtenerMoneda()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SS_DDJJ_ObtenerMoneda_Result>("SS_DDJJ_ObtenerMoneda");
        }
    
        public virtual ObjectResult<SS_DDJJ_ObtenerCodigoMovto_Result> SS_DDJJ_ObtenerCodigoMovto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SS_DDJJ_ObtenerCodigoMovto_Result>("SS_DDJJ_ObtenerCodigoMovto");
        }
    
        public virtual ObjectResult<SS_DDJJ_ObtenerMovto_Result> SS_DDJJ_ObtenerMovto(Nullable<int> iD_DDJJ)
        {
            var iD_DDJJParameter = iD_DDJJ.HasValue ?
                new ObjectParameter("ID_DDJJ", iD_DDJJ) :
                new ObjectParameter("ID_DDJJ", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SS_DDJJ_ObtenerMovto_Result>("SS_DDJJ_ObtenerMovto", iD_DDJJParameter);
        }
    
        public virtual ObjectResult<SS_DDJJ_ObtenerDJ_Result> SS_DDJJ_ObtenerDJ()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SS_DDJJ_ObtenerDJ_Result>("SS_DDJJ_ObtenerDJ");
        }
        public virtual ObjectResult<SS_DDJJ_ListaTipoEvento_Result> SS_DDJJ_ListaTipoEvento(Nullable<int> iD_TipoEvento)
        {
            var iD_TipoEventoParameter = iD_TipoEvento.HasValue ?
                new ObjectParameter("ID_TipoEvento", iD_TipoEvento) :
                new ObjectParameter("ID_TipoEvento", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SS_DDJJ_ListaTipoEvento_Result>("SS_DDJJ_ListaTipoEvento", iD_TipoEventoParameter);
        }
    }
}
